### PR TITLE
Update to QuickJS-ng

### PR DESCRIPTION
**Pull request by saghul**
https://github.com/quickjs-ng/quickjs

### CODE REVIEW

**Comment by justjake** [comment]
If we don’t need any build system changes here though, I’d consider switching over. What is the advantage of quickjs-ng over the original? I see BigFloat/BigDecimal was removed and BigInt made unconditional (seems good) and a switch to CMake (it’s fine as long as it doesn’t affect me). I also see some discussion of moving source files around, which I seems like needless breakage.

**Comment by justjake** [comment]
Is there discussion of quickjs-ng on the quickjs-devel  mailing list?

**Comment by saghul** [comment]
Hey there! We've added many new ES features like top level await, multiple array and object methods, weakref, etc.

So far we have tried to keep this "as they were" for the most part :-) 

I have personally reached out to the original authors and got a positive reply, looks like there won't be further development in the original project.

**Comment by saghul** [comment]
Interesting the stack check tests fail. In the original project it's if-defd out on emscripten but I now realize you were overrridin that. Does it work? If so I guess we could just remove the gating in NG.

**Comment by justjake** [comment]
I think the gating may be due to a desire to limit size of emscripten build by default, but I'm not sure. It seems to work in my tests. I did notice today when publishing the new version that the DEBUG_ASYNCIFY variant now fails with some stack issue, i reduced the number of frames we need to support there (DEBUG_ASYNCIFY is quite inefficient...)

**Comment by justjake** [comment]
Closing in favor of #135

**Pull request closed without merging**
