### PR TITLE
updated to quickjs-2020-04-12

### PR DESCRIPTION
**Pull request by abner**

### CODE REVIEW

**Comment by atifsyedali** [comment]
@justjake Is it possible for you to merge this in / update quickjs to latest and publish to npm?

**Comment by justjake** [comment]
published 0.3.0

**Comment by justjake** [comment]
apologies for not merging! i ended up running the update script myself because version bump PRs are difficult to review easily.

**Comment by justjake** [comment]
Closing as I think the issue is resolved.

**Comment by atifsyedali** [comment]
Thanks!

**Pull request closed without merging**
